<div class="modal" id="payModal">
    <div class="modal-content" style="width: 900px; max-width: 95%;">
        <div class="modal-header">
            <h3 id="payModalTitle">Payment</h3>
            <span class="close" onclick="closePayModal()">✕</span>
        </div>
        <form action="{{ route('payments.store') }}" method="POST" id="paymentForm" onsubmit="preparePaymentDetails()"
            target="_blank">
            @csrf
            <!-- Method Spoofing for Edit (Dynamic) -->
            <div id="methodSpoofContainer"></div>

            <input type="hidden" name="student_id" id="payStudentId">
            <input type="hidden" name="payment_type" id="paymentType" value="Monthly">
            <input type="hidden" name="redirect_to" value="students.receipt.confirm">
            <input type="hidden" name="show_receipt" value="1">

            <!-- Hidden inputs for detailed payment breakdown -->
            <input type="hidden" name="payment_details" id="paymentDetailsInput">
            <input type="hidden" name="selected_months" id="selectedMonthsInput">
            <input type="hidden" name="added_fees" id="addedFeesInput">

            <div style="display:flex; gap: 16px; margin-bottom:12px; flex-wrap:wrap">
                <div style="flex: 2; min-width: 200px;">
                    <label>Student</label>
                    <input type="text" id="payStudentName" readonly style="background:#15181a;cursor:not-allowed">
                </div>
                <div style="flex: 2; min-width: 200px;">
                    <label>Father's Name</label>
                    <input type="text" id="payFatherName" readonly style="background:#15181a;cursor:not-allowed">
                </div>
                <div style="flex: 1; min-width: 150px;">
                    <label>Date</label>
                    <input type="date" name="payment_date" id="paymentDateInput" value="{{ date('Y-m-d') }}" required
                        onchange="updatePeriod()">
                </div>
                <div style="flex: 1; min-width: 150px;">
                    <label>Category</label>
                    <select id="feeCategorySelect" onchange="updateFeeViews()" required>
                        <option value="Monthly" selected>Monthly</option>
                        <option value="Quarterly">Quarterly</option>
                        <option value="Half-Yearly">Half-Yearly</option>
                        <option value="Yearly">Yearly</option>
                    </select>
                </div>

                <!-- Month Selection Dropdown (Visible only for Monthly) -->
                <div style="flex: 1; min-width: 150px; display:none;" id="monthSelectionContainer">
                    <label>Select Months</label>
                    <div style="position:relative;">
                        <div id="monthDropdownBtn" onclick="toggleMonthDropdown()"
                            style="background:#1b1f22; padding:8px; border:1px solid rgba(255,255,255,0.15); border-radius:4px; cursor:pointer; display:flex; justify-content:space-between; align-items:center; height: 35px; box-sizing: border-box;">
                            <span id="selectedMonthsText"
                                style="white-space:nowrap; overflow:hidden; text-overflow:ellipsis; font-size:13px;">Select
                                Months</span>
                            <span style="font-size:10px">▼</span>
                        </div>
                        <div id="monthDropdownList"
                            style="display:none; position:absolute; top:100%; left:0; width:100%; background:#1b1f22; border:1px solid rgba(255,255,255,0.15); border-radius:4px; z-index:1000; max-height:200px; overflow-y:auto; box-shadow: 0 4px 6px rgba(0,0,0,0.3);">
                            <!-- Checkboxes generated by JS -->
                        </div>
                    </div>
                </div>

                <input type="hidden" name="month" id="hiddenMonthInput">
            </div>

            <div style="margin-bottom:16px">
                <label>Fees</label>
                <div style="border: 1px solid rgba(255,255,255,0.15); border-radius: 4px; overflow: visible;">
                    <table style="width:100%; margin:0;">
                        <thead style="background:rgba(255,255,255,0.05)">
                            <tr>
                                <th style="text-align:left; padding: 10px;">Description</th>
                                <th style="text-align:right; padding: 10px;">Actual Fee</th>
                                <th style="text-align:right; padding: 10px;">Discounted Fee</th>
                            </tr>
                        </thead>
                        <tbody id="monthlyFeeTableBody">
                            <!-- Populated via JS -->
                        </tbody>
                    </table>
                </div>
            </div>

            <div style="display:flex; gap: 20px; flex-wrap:wrap">
                <!-- Left: Other Fees -->
                <div style="flex: 1; min-width: 250px;">
                    <label style="margin-bottom: 8px; display:block;">Other Fees</label>
                    <div id="otherFeesContainer"
                        style="background:rgba(255,255,255,0.05); padding: 10px; border-radius: 4px; max-height: 200px; overflow-y: auto; border: 1px solid rgba(255,255,255,0.1);">
                        <!-- Checkboxes populated via JS -->
                    </div>
                </div>

                <!-- Right: Summary -->
                <div style="width: 300px; min-width: 250px;">
                    <div
                        style="background:rgba(255,255,255,0.05); padding: 15px; border-radius: 4px; border: 1px solid rgba(255,255,255,0.1);">
                        <div style="display:flex; justify-content:space-between; margin-bottom: 8px;">
                            <span style="color:var(--muted)">Subtotal</span>
                            <span id="summarySubtotal" style="font-weight:bold">৳ 0.00</span>
                        </div>
                        <div
                            style="display:flex; justify-content:space-between; align-items:center; margin-bottom: 8px;">
                            <span style="color:var(--muted)">Discount</span>
                            <input type="number" id="manualDiscountInput" value="0" min="0"
                                oninput="calculateTotal()"
                                style="width: 100px; text-align:right; padding: 6px; background:rgba(0,0,0,0.2); border:1px solid rgba(255,255,255,0.1); color:var(--text); border-radius:4px;">
                        </div>
                        <div style="border-top: 1px solid rgba(255,255,255,0.1); margin: 8px 0;"></div>

                        <div
                            style="display:flex; justify-content:space-between; align-items:center; margin-bottom: 8px;">
                            <span style="font-weight:bold; font-size: 16px;">Total Amount</span>
                            <input type="number" name="amount" id="payAmountInput" readonly
                                style="width: 120px; text-align:right; font-weight:bold; color:var(--accent); background:rgba(0,0,0,0.2); border:1px solid var(--accent); border-radius:4px; padding:6px;">
                        </div>
                    </div>

                    <div style="margin-top: 12px;">
                        <label>Payment Mode</label>
                        <select name="payment_mode" required>
                            <option value="Cash">Cash</option>
                            <option value="Bkash">Bkash</option>
                            <option value="Bank">Bank</option>
                            <option value="Rocket">Rocket</option>
                            <option value="Upay">Upay</option>
                            <option value="Others">Others</option>
                        </select>
                    </div>
                    <div style="margin-top: 12px;">
                        <label>Note</label>
                        <input type="text" name="note" placeholder="Optional note">
                    </div>
                </div>
            </div>

            <div style="text-align:right; margin-top: 20px;">
                <button type="button" class="btn ghost" onclick="closePayModal()">Cancel</button>
                <button type="submit" class="btn">Confirm Payment</button>
            </div>
        </form>
    </div>
</div>

<script>
    let currentFees = [];
    let currentDiscounts = {};
    let allFees = [];
    let currentSubscribedFees = [];
    let currentNetPayable = 0;
    let currentPaidFeeTracker = {};
    let availableClassFees = [];

    function openPayModal(id, name, fatherName, selectedFees, discounts, paidFeeTracker, classFees, partialPayments) {
        // Reset Redirect to default (Receipt)
        const redirectInput = document.querySelector('input[name="redirect_to"]');
        if (redirectInput) redirectInput.value = 'students.receipt.confirm';

        // fees = selectedFees (what student has subscribed to)
        // classFees = all available fees for the class
        // partialPayments = fees with remaining balance

        // Store subscriptions globally - these are the 'defaults'
        currentSubscribedFees = selectedFees || [];

        // Initialize 'allFees' (Active Payment Fees)
        // Include all monthly fees from class, not just subscribed ones
        // This ensures we can properly track payment status for each month
        const monthlyFeesFromClass = (classFees || []).filter(f => (f.type || '').toLowerCase() === 'monthly');
        const monthlyFeesFromSelected = (selectedFees || []).filter(f => (f.type || 'Monthly').toLowerCase() ===
            'monthly');

        // Combine and deduplicate monthly fees based on name
        const monthlyFeesMap = {};
        [...monthlyFeesFromClass, ...monthlyFeesFromSelected].forEach(fee => {
            if (!monthlyFeesMap[fee.name]) {
                monthlyFeesMap[fee.name] = fee;
            }
        });
        allFees = Object.values(monthlyFeesMap);


        // Ensure all subscribed fees are available in the pool even if not active in table
        availableClassFees = [...(classFees || [])];
        (selectedFees || []).forEach(sf => {
            if (!availableClassFees.some(af => af.name === sf.name)) {
                availableClassFees.push(sf);
            }
        });

        currentDiscounts = discounts || {};
        currentPaidFeeTracker = paidFeeTracker || {};


        // Add unpaid admission fees to availableClassFees
        if (partialPayments && typeof partialPayments === 'object') {
            for (let feeName in partialPayments) {
                const partial = partialPayments[feeName];
                if (partial.remaining && partial.remaining > 0) {
                    // Add to available fees with remaining amount
                    availableClassFees.push({
                        name: feeName + ' (Remaining)',
                        type: 'One Time',
                        amount: partial.remaining,
                        is_partial_completion: true,
                        original_total: partial.total,
                        already_paid: partial.paid
                    });
                }
            }
        }

        document.getElementById('payStudentId').value = id;
        document.getElementById('payStudentName').value = name;
        document.getElementById('payFatherName').value = fatherName;
        document.getElementById('feeCategorySelect').value = 'Monthly'; // Default
        document.getElementById('feeCategorySelect').setAttribute('onchange', 'handleCategoryChange()');
        document.getElementById('manualDiscountInput').value = 0;

        // Always set date to today when opening the modal
        document.getElementById('paymentDateInput').value = new Date().toISOString().split('T')[0];

        // Reset Form Action to Store
        const form = document.getElementById('paymentForm');
        form.action = "{{ route('payments.store') }}";
        document.getElementById('methodSpoofContainer').innerHTML = ''; // Clear method spoofing (PUT)

        updateFeeViews();
        document.getElementById('payModal').style.display = 'flex';
    }

    function handleCategoryChange() {
        const newCategory = document.getElementById('feeCategorySelect').value;
        const previousCategory = document.getElementById('paymentType').value || 'Monthly';

        // Remove fees belonging to the PREVIOUS main category
        let remainingFees = allFees.filter(f => (f.type || '').toLowerCase() !== previousCategory.toLowerCase());

        // Add fees that belong to the NEW main category (from Subscriptions)
        const newMainFees = currentSubscribedFees.filter(f => (f.type || '').toLowerCase() === newCategory
            .toLowerCase());

        // Combine (avoid duplicates)
        newMainFees.forEach(newFee => {
            if (!remainingFees.some(existing => existing.name === newFee.name)) {
                remainingFees.push(newFee);
            }
        });

        allFees = remainingFees;
        updateFeeViews();
    }

    function closePayModal() {
        document.getElementById('payModal').style.display = 'none';
    }

    // Toggle custom part dropdown
    function togglePartDropdown(id) {
        const menu = document.getElementById('menu_' + id);
        if (menu) menu.style.display = (menu.style.display === 'none' ? 'block' : 'none');
    }

    // Global click to close
    document.addEventListener('click', function(e) {
        if (!e.target.closest('.part-dropdown-container')) {
            document.querySelectorAll('.part-dropdown-menu').forEach(m => m.style.display = 'none');
        }
    });

    // Update selection from checkboxes
    function updatePartSelection(chk, id) {
        const container = document.getElementById('part_container_' + id);
        const tr = container.closest('tr');

        // Get all checked
        const menu = document.getElementById('menu_' + id);
        const checked = menu.querySelectorAll('input[type="checkbox"]:checked');
        const values = Array.from(checked).map(c => c.value);

        // Update Display
        const disp = document.getElementById('disp_' + id);
        if (values.length === 0) disp.innerText = 'None';
        else if (values.length === 1) disp.innerText = values[0];
        else disp.innerText = values.length + ' Selected';

        // Update Row Data
        tr.dataset.partName = values.join(', ');

        // Update Amount logic
        const unitAmount = parseFloat(tr.dataset.unitAmount) || parseFloat(tr.dataset.actual) || 0;
        if (!tr.dataset.unitAmount) tr.dataset.unitAmount = unitAmount;

        const count = Math.max(0, values.length);
        const newTotal = unitAmount * count;

        tr.dataset.actual = newTotal;

        // Update Text in Row
        const tds = tr.querySelectorAll('td');
        if (tds[1]) tds[1].innerText = '৳' + newTotal.toFixed(2);

        // Update Discounted Column
        const discount = parseFloat(tr.dataset.discount) || 0;
        const discounted = Math.max(0, newTotal - discount);
        if (tds[2]) {
            const span = tds[2].querySelector('span');
            if (span) span.innerText = '৳' + discounted.toFixed(2);
        }

        calculateTotal();
    }

    // Helper to generate dropdown for split fees
    function generatePartDropdown(type, feeName) {
        let options = [];
        const t = (type || '').toLowerCase();

        if (t.includes('quarterly')) {
            options = ['1st Quater', '2nd Quater', '3rd Quater', '4th Quater'];
        } else if (t.includes('half')) {
            options = ['1st Half', '2nd Half'];
        } else {
            return null;
        }

        const uniqueId = 'pdd_' + Math.floor(Math.random() * 100000);

        let html =
            `<div id="part_container_${uniqueId}" class="part-dropdown-container" style="position:relative; display:inline-block; margin-left:12px;">
        <div onclick="togglePartDropdown('${uniqueId}')" style="background:#2b2f33; border:1px solid #444; color:white; padding:4px 8px; font-size:11px; border-radius:4px; cursor:pointer; min-width:110px; display:flex; justify-content:space-between; align-items:center;">
            <span id="disp_${uniqueId}">Select Part</span>
            <span>▼</span>
        </div>
        <div id="menu_${uniqueId}" class="part-dropdown-menu" style="display:none; position:absolute; top:100%; left:0; width:100%; min-width:120px; background:#252629; border:1px solid #444; z-index:99999; max-height:150px; overflow-y:auto; box-shadow:0 4px 12px rgba(0,0,0,0.5);">`;

        let firstUnpaid = null;

        options.forEach(opt => {
            const key = feeName.trim() + ' - ' + opt;
            let isPaid = !!currentPaidFeeTracker[key];

            let checked = '';
            if (!isPaid && !firstUnpaid) {
                firstUnpaid = opt;
                checked = 'checked';
            }

            html += `<label style="display:block; padding:6px 8px; cursor:pointer; font-size:11px; border-bottom:1px solid #333; margin:0;">
            <input type="checkbox" value="${opt}" onchange="updatePartSelection(this, '${uniqueId}')" ${isPaid ? 'disabled' : ''} ${checked}>
            <span style="opacity:${isPaid ? 0.5 : 1}">${opt} ${isPaid ? '(Paid)' : ''}</span>
        </label>`;
        });

        html += `</div></div>`;

        const defaultText = firstUnpaid || 'Select Part';
        html = html.replace('Select Part', defaultText);

        return {
            html: html,
            default: firstUnpaid || ''
        };
    }

    function updateFeeViews() {
        const category = document.getElementById('feeCategorySelect').value;
        document.getElementById('paymentType').value = category;

        updatePeriod();

        let activeMainFees;
        if (category === 'Monthly') {
            activeMainFees = allFees.filter(f => (f.type || 'Monthly').toLowerCase() === 'monthly');
        } else {
            activeMainFees = allFees.filter(f => (f.type || '').toLowerCase() === category.toLowerCase());
        }

        const tbody = document.getElementById('monthlyFeeTableBody');
        tbody.innerHTML = '';

        // 1. Render Active Main Fees
        activeMainFees.forEach((fee, index) => {
            const discount = getDiscount(fee.name);
            const actual = parseFloat(fee.amount) || 0;
            const discounted = Math.max(0, actual - discount);

            const splitData = generatePartDropdown(fee.type, fee.name);
            const dropdownHtml = splitData ? splitData.html : '';
            const initialPart = splitData ? splitData.default : '';

            const tr = document.createElement('tr');
            tr.className = 'main-fee-row';
            tr.dataset.type = fee.type || category;
            tr.dataset.actual = actual;
            tr.dataset.unitAmount = actual;
            tr.dataset.discount = discount;
            tr.dataset.feeName = fee.name;
            if (initialPart) tr.dataset.partName = initialPart;

            tr.style.borderBottom = '1px solid rgba(255,255,255,0.05)';
            tr.style.transition = 'all 0.3s ease';
            tr.innerHTML = `
        <td style="text-align:left; padding: 10px;">
            <div style="display:flex; align-items:center; justify-content:flex-start; gap:15px; flex-wrap:nowrap;">
                <span style="font-weight:500;">${fee.name}</span>
                ${dropdownHtml}
            </div>
        </td>
        <td style="text-align:right; padding: 10px;">৳${actual.toFixed(2)}</td>
        <td style="text-align:right; padding: 10px;">
          <div style="display:flex; align-items:center; justify-content:flex-end; gap:8px;">
            <span style="font-weight:bold; color:var(--text);">৳${discounted.toFixed(2)}</span>
            <button type="button" onclick="removeMainFee('${fee.name}')"
                    class="action-btn delete" style="padding:4px 8px; font-size:11px;">✕ Remove</button>
          </div>
        </td>
      `;
            tbody.appendChild(tr);
        });

        // 2. Render Active Other Fees
        const activeOtherFees = allFees.filter(f => (f.type || '').toLowerCase() !== category.toLowerCase());

        activeOtherFees.forEach((fee) => {
            const discount = getDiscount(fee.name);
            const actual = parseFloat(fee.amount) || 0;
            const discounted = Math.max(0, actual - discount);

            const isPartial = fee.is_partial_completion === true;

            const splitData = generatePartDropdown(fee.type, fee.name);
            const dropdownHtml = splitData ? splitData.html : '';
            const initialPart = splitData ? splitData.default : '';

            const tr = document.createElement('tr');
            tr.className = 'added-other-fee';
            tr.setAttribute('data-fee-name', fee.name);
            tr.dataset.actual = actual;
            tr.dataset.discount = discount;
            tr.dataset.unitAmount = actual;
            tr.dataset.isPartial = isPartial ? 'true' : 'false';
            if (initialPart) tr.dataset.partName = initialPart;

            tr.style.borderBottom = '1px solid rgba(255,255,255,0.05)';

            const amountDisplay = isPartial ?
                `<input type="number" value="${discounted}"
                  oninput="updatePartialAmount(this)"
                  style="width:80px; background:#1b1f22; color:white; border:1px solid #444; border-radius:4px; padding:4px; text-align:right;"
                  step="0.01" min="0" max="${actual}">` :
                `৳${discounted.toFixed(2)}`;

            tr.innerHTML = `
        <td style="text-align:left; padding: 10px;">
           <div style="display:flex; align-items:center; justify-content:flex-start; gap:15px; flex-wrap:nowrap;">
               <div>
                  ${fee.name} (${fee.type})
                  <span style="background:rgba(227,120,20,0.3); color:var(--accent); padding:2px 6px; border-radius:3px; font-size:11px; margin-left:8px;">ADDED</span>
               </div>
               ${dropdownHtml}
           </div>
        </td>
        <td style="text-align:right; padding: 10px;">৳${actual.toFixed(2)}</td>
        <td style="text-align:right; padding: 10px;">
          <div style="display:flex; align-items:center; justify-content:flex-end; gap:8px;">
            <span style="font-weight:bold; color:var(--text);">${amountDisplay}</span>
            <button type="button" onclick="removeAddedFee('${fee.name}')"
                    class="action-btn delete" style="padding:4px 8px; font-size:11px;">✕ Remove</button>
          </div>
        </td>
      `;
            tbody.appendChild(tr);
        });

        // Check if empty
        if (tbody.children.length === 0) {
            tbody.innerHTML =
                '<tr><td colspan="3" style="text-align:center; color:var(--muted)">No fees selected</td></tr>';
        }

        // 3. Render Other Fees List
        const inactiveFees = availableClassFees.filter(af => !allFees.some(f => f.name === af.name));

        const combinedOtherFees = [
            ...activeOtherFees.map(f => ({
                ...f,
                _isActive: true
            })),
            ...inactiveFees.map(f => ({
                ...f,
                _isActive: false
            }))
        ];

        const otherContainer = document.getElementById('otherFeesContainer');
        otherContainer.innerHTML = '';

        let visibleCount = 0;

        combinedOtherFees.forEach((fee, index) => {
            const discount = getDiscount(fee.name);
            const actual = parseFloat(fee.amount) || 0;
            const discounted = Math.max(0, actual - discount);
            const isChecked = fee._isActive;

            const div = document.createElement('div');
            div.style.marginBottom = '8px';
            div.className = 'other-fee-item';
            const isPartialFee = fee.is_partial_completion === true;

            div.setAttribute('data-fee-name', fee.name);
            div.setAttribute('data-actual', actual);
            div.setAttribute('data-discount', discount);
            div.setAttribute('data-discounted', discounted);
            div.setAttribute('data-type', fee.type);
            div.setAttribute('data-is-partial', isPartialFee ? 'true' : 'false');

            if (isChecked) {
                div.style.display = 'none';
            } else {
                div.style.display = 'block';
                visibleCount++;
            }

            const partialBadge = isPartialFee ?
                `<span style="background:rgba(255,193,7,0.3); color:#ffc107; padding:2px 6px; border-radius:3px; font-size:10px; margin-left:4px; font-weight:600;">DUE</span>` :
                '';

            div.innerHTML = `
        <div style="display:flex; align-items:center; gap: 8px; cursor:pointer; padding: 6px 8px; border-radius: 4px; background:${isChecked ? 'rgba(227,120,20,0.15)' : (isPartialFee ? 'rgba(255,193,7,0.08)' : 'rgba(255,255,255,0.02)')}; ${isPartialFee ? 'border: 1px solid rgba(255,193,7,0.3);' : ''} user-select:none;"
             onclick="toggleOtherFee(this)">
            <input type="checkbox" class="fee-checkbox other-fee-checkbox"
                   data-fee-name="${fee.name}"
                   ${isChecked ? 'checked' : ''}
                   style="opacity:0; position:absolute; pointer-events:none;">
            <span style="font-size:13px; flex:1;">${fee.name} (${fee.type})${partialBadge}</span>
            <span style="font-size:13px; color:${isPartialFee ? '#ffc107' : 'var(--accent)'}; font-weight:500;">৳${discounted.toFixed(2)}</span>
        </div>
      `;

            div.onmouseover = function() {
                const input = this.querySelector('input');
                const innerDiv = this.querySelector('div');
                if (!input.checked) {
                    innerDiv.style.background = isPartialFee ? 'rgba(255,193,7,0.15)' :
                        'rgba(255,255,255,0.05)';
                }
            };
            div.onmouseout = function() {
                const input = this.querySelector('input');
                const innerDiv = this.querySelector('div');
                if (!input.checked) {
                    innerDiv.style.background = isPartialFee ? 'rgba(255,193,7,0.08)' :
                        'rgba(255,255,255,0.02)';
                }
            };

            otherContainer.appendChild(div);
        });

        if (visibleCount === 0 && combinedOtherFees.length > 0) {
            const msg = document.createElement('div');
            msg.style.color = 'var(--muted)';
            msg.innerText = 'All fees added';
            msg.style.textAlign = 'center';
            msg.style.padding = '10px';
            otherContainer.appendChild(msg);
        } else if (combinedOtherFees.length === 0) {
            otherContainer.innerHTML =
                '<div style="color:var(--muted); text-align:center; padding:10px">No other fees available</div>';
        }

        calculateTotal();
    }

    function removeAddedFee(feeName) {
        allFees = allFees.filter(f => f.name !== feeName);
        const tbody = document.getElementById('monthlyFeeTableBody');
        const existingRow = tbody.querySelector(`tr[data-fee-name="${feeName}"]`);

        if (existingRow) {
            existingRow.remove();
            const checkbox = document.querySelector(`.other-fee-checkbox[data-fee-name="${feeName}"]`);
            if (checkbox) {
                checkbox.checked = false;
                const feeItem = checkbox.closest('.other-fee-item');
                if (feeItem) {
                    feeItem.style.display = 'block';
                    feeItem.querySelector('div').style.background = 'rgba(255,255,255,0.02)';
                }
            }
            calculateTotal();
        }
    }

    function removeMainFee(feeName) {
        allFees = allFees.filter(f => f.name !== feeName);
        const tbody = document.getElementById('monthlyFeeTableBody');
        const existingRow = tbody.querySelector(`tr[data-fee-name="${feeName}"]`);

        if (existingRow) {
            existingRow.remove();
            const otherContainer = document.getElementById('otherFeesContainer');
            let feeItem = otherContainer.querySelector(`.other-fee-item[data-fee-name="${feeName}"]`);

            if (feeItem) {
                const checkbox = feeItem.querySelector('input[type="checkbox"]');
                if (checkbox) checkbox.checked = false;
                feeItem.style.display = 'block';
                feeItem.querySelector('div').style.background = 'rgba(255,255,255,0.02)';
            } else {
                addNewInactiveFeeListItem(feeName, existingRow.dataset.actual, existingRow.dataset.discount);
            }
            calculateTotal();
        }
    }

    function addNewInactiveFeeListItem(name, actual, discount) {
        const otherContainer = document.getElementById('otherFeesContainer');
        const category = document.getElementById('feeCategorySelect').value;
        const discounted = Math.max(0, actual - discount);

        const div = document.createElement('div');
        div.style.marginBottom = '8px';
        div.className = 'other-fee-item';
        div.setAttribute('data-fee-name', name);
        div.setAttribute('data-actual', actual);
        div.setAttribute('data-discount', discount);
        div.setAttribute('data-discounted', discounted);
        div.setAttribute('data-type', category);

        div.innerHTML = `
      <div style="display:flex; align-items:center; gap: 8px; cursor:pointer; padding: 6px 8px; border-radius: 4px; background:rgba(255,255,255,0.02); user-select:none;"
           onclick="toggleOtherFee(this)">
          <input type="checkbox" class="fee-checkbox other-fee-checkbox"
                 data-fee-name="${name}"
                 style="opacity:0; position:absolute; pointer-events:none;">
          <span style="font-size:13px; flex:1;">${name} (${category})</span>
          <span style="font-size:13px; color:var(--accent); font-weight:500;">৳${discounted.toFixed(2)}</span>
      </div>
    `;
        otherContainer.appendChild(div);
    }

    function toggleOtherFee(container) {
        const checkbox = container.querySelector('input[type="checkbox"]');
        const feeName = checkbox.getAttribute('data-fee-name');
        const isAlreadySelected = allFees.some(f => f.name === feeName);
        const feeItem = container.closest('.other-fee-item');
        const tbody = document.getElementById('monthlyFeeTableBody');

        if (isAlreadySelected) {
            allFees = allFees.filter(f => f.name !== feeName);
            checkbox.checked = false;
            if (feeItem) {
                const innerDiv = feeItem.querySelector('div');
                if (innerDiv) innerDiv.style.background = 'rgba(255,255,255,0.02)';
            }
            const existingRow = tbody.querySelector(`tr[data-fee-name="${feeName}"]`);
            if (existingRow) existingRow.remove();
        } else {
            const actual = parseFloat(feeItem.getAttribute('data-actual')) || 0;
            const discount = parseFloat(feeItem.getAttribute('data-discount')) || 0;
            const feeType = (feeItem.getAttribute('data-type') || 'Other');
            const currentCategory = (document.getElementById('feeCategorySelect').value || '').toLowerCase();
            const isPartial = feeItem.getAttribute('data-is-partial') === 'true';

            allFees.push({
                name: feeName,
                amount: actual,
                type: feeType,
                is_partial_completion: isPartial
            });

            checkbox.checked = true;
            let tr = document.createElement('tr');
            tr.setAttribute('data-fee-name', feeName);
            tr.style.borderBottom = '1px solid rgba(255,255,255,0.05)';

            if (feeType.toLowerCase() === currentCategory) {
                const splitData = generatePartDropdown(feeType, feeName);
                const dropdownHtml = splitData ? splitData.html : '';
                const initialPart = splitData ? splitData.default : '';

                tr.className = 'main-fee-row';
                tr.dataset.actual = actual;
                tr.dataset.unitAmount = actual;
                tr.dataset.discount = discount;
                tr.dataset.feeName = feeName;
                if (initialPart) tr.dataset.partName = initialPart;

                tr.innerHTML = `
        <td style="text-align:left; padding: 10px;">
            <div style="display:flex; align-items:center; justify-content:flex-start; gap:15px; flex-wrap:nowrap;">
                <span style="font-weight:500;">${feeName}</span>
                ${dropdownHtml}
            </div>
        </td>
        <td style="text-align:right; padding: 10px;">৳${actual.toFixed(2)}</td>
        <td style="text-align:right; padding: 10px;">
          <div style="display:flex; align-items:center; justify-content:flex-end; gap:8px;">
            <span style="font-weight:bold; color:var(--text);">৳${(Math.max(0, actual-discount)).toFixed(2)}</span>
            <button type="button" onclick="removeMainFee('${feeName}')"
                    class="action-btn delete" style="padding:4px 8px; font-size:11px;">✕ Remove</button>
          </div>
        </td>
      `;
            } else {
                const discounted = Math.max(0, actual - discount);
                tr.className = 'added-other-fee';
                tr.dataset.actual = actual;
                tr.dataset.discount = discount;
                tr.dataset.isPartial = isPartial ? 'true' : 'false';

                const amountDisplay = isPartial ?
                    `<input type="number" value="${discounted}"
                  oninput="updatePartialAmount(this)"
                  style="width:80px; background:#1b1f22; color:white; border:1px solid #444; border-radius:4px; padding:4px; text-align:right;"
                  step="0.01" min="0" max="${actual}">` :
                    `৳${discounted.toFixed(2)}`;

                tr.innerHTML = `
        <td style="text-align:left; padding: 10px;">
           <div style="display:flex; align-items:center; justify-content:flex-start; gap:15px; flex-wrap:nowrap;">
               <div>
                  ${feeName} (${feeType})
                  <span style="background:rgba(227,120,20,0.3); color:var(--accent); padding:2px 6px; border-radius:3px; font-size:11px; margin-left:8px;">ADDED</span>
               </div>
           </div>
        </td>
        <td style="text-align:right; padding: 10px;">৳${actual.toFixed(2)}</td>
        <td style="text-align:right; padding: 10px;">
          <div style="display:flex; align-items:center; justify-content:flex-end; gap:8px;">
            <span style="font-weight:bold; color:var(--text);">${amountDisplay}</span>
            <button type="button" onclick="removeAddedFee('${feeName}')"
                    class="action-btn delete" style="padding:4px 8px; font-size:11px;">✕ Remove</button>
          </div>
        </td>
      `;
            }
            tbody.appendChild(tr);
            feeItem.style.display = 'none';
        }
        calculateTotal();
    }

    function getDiscount(feeName) {
        if (!currentDiscounts || !feeName) return 0;
        const targetName = feeName.toString().trim().toLowerCase();
        if (currentDiscounts[feeName]) {
            const d = currentDiscounts[feeName];
            return typeof d === 'object' ? (parseFloat(d.amount) || 0) : (parseFloat(d) || 0);
        }
        for (let key in currentDiscounts) {
            if (key.toString().trim().toLowerCase() === targetName) {
                const d = currentDiscounts[key];
                return typeof d === 'object' ? (parseFloat(d.amount) || 0) : (parseFloat(d) || 0);
            }
        }
        return 0;
    }

    document.addEventListener('click', function(e) {
        const container = document.getElementById('monthSelectionContainer');
        const dropdown = document.getElementById('monthDropdownList');
        if (container.style.display !== 'none' && !container.contains(e.target)) {
            dropdown.style.display = 'none';
        }
    });

    function toggleMonthDropdown() {
        const dropdown = document.getElementById('monthDropdownList');
        dropdown.style.display = dropdown.style.display === 'block' ? 'none' : 'block';
    }

    function updatePeriod() {
        const dateInput = document.getElementById('paymentDateInput');
        const category = document.getElementById('feeCategorySelect').value;
        const hiddenMonth = document.getElementById('hiddenMonthInput');
        const monthContainer = document.getElementById('monthSelectionContainer');

        if (!dateInput.value) return;

        const date = new Date(dateInput.value);
        const monthIndex = date.getMonth();
        const year = date.getFullYear();
        let period = '';

        if (category === 'Monthly') {
            monthContainer.style.display = 'block';
            const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September',
                'October', 'November', 'December'
            ];
            const orderedMonths = [];
            for (let i = 0; i < 12; i++) {
                const currentMonthIndex = (monthIndex + i) % 12;
                const monthName = months[currentMonthIndex];
                const monthYear = year + Math.floor((monthIndex + i) / 12);
                const shortYear = monthYear.toString().slice(-2);
                orderedMonths.push({
                    name: monthName,
                    year: shortYear,
                    displayText: `${monthName}, ${shortYear}`
                });
            }

            const dropdownList = document.getElementById('monthDropdownList');
            dropdownList.innerHTML = '';

            orderedMonths.forEach((monthObj, index) => {
                const displayText = monthObj.displayText;
                const paidFeesForThisMonth = currentPaidFeeTracker[displayText] || [];

                // Get the current monthly fees being displayed (which fees the student is subscribed to)
                const monthlyFees = allFees.filter(f => (f.type || '').toLowerCase() === 'monthly');
                const totalMonthlyFees = monthlyFees.length;
                const monthlyFeeNames = monthlyFees.map(f => f.name.toLowerCase());

                let paidCount = 0;
                if (Array.isArray(paidFeesForThisMonth)) {
                    // If it's an array, it contains fee names or __ALL__
                    if (paidFeesForThisMonth.includes('__ALL__')) {
                        paidCount = totalMonthlyFees;
                    } else {
                        // Count how many of the current monthly fees have been paid
                        paidCount = paidFeesForThisMonth.filter(pf => monthlyFeeNames.includes(pf
                            .toLowerCase())).length;
                    }
                }

                let status = 'unpaid';
                if (totalMonthlyFees > 0) {
                    if (paidCount >= totalMonthlyFees) status = 'paid';
                    else if (paidCount > 0) status = 'partial';
                } else if (paidCount > 0 || (Array.isArray(paidFeesForThisMonth) && paidFeesForThisMonth
                        .includes('__ALL__'))) {
                    status = 'paid';
                }

                const isFullyPaid = status === 'paid';
                const isChecked = false;

                const div = document.createElement('div');
                div.style.padding = '8px';
                div.style.cursor = isFullyPaid ? 'not-allowed' : 'pointer';
                div.style.borderBottom = '1px solid rgba(255,255,255,0.05)';
                div.style.background = isFullyPaid ? 'rgba(255,255,255,0.02)' : 'transparent';

                let badge = '';
                if (status === 'paid') badge =
                    '<span style="font-size:10px; background:rgba(76,175,80,0.2); color:#4caf50; padding:1px 4px; border-radius:3px; margin-left:6px; border:1px solid #4caf50;">PAID</span>';
                else if (status === 'partial') badge =
                    '<span style="font-size:10px; background:rgba(255,193,7,0.2); color:#ffc107; padding:1px 4px; border-radius:3px; margin-left:6px; border:1px solid #ffc107;">PARTIAL</span>';

                div.innerHTML = `
                <label style="cursor:${isFullyPaid ? 'not-allowed' : 'pointer'}; display:flex; align-items:center; width:100%; margin:0; ${isFullyPaid ? 'opacity:0.6;' : ''}">
                    <input type="checkbox" value="${monthObj.name}" class="month-checkbox"
                           data-year="${monthObj.year}"
                           data-display-text="${monthObj.displayText}"
                           ${isChecked ? 'checked' : ''}
                           ${isFullyPaid ? 'disabled' : ''}
                           onchange="updateSelectedMonths()">
                    <span style="margin-left:8px">${monthObj.displayText}${badge}</span>
                </label>
            `;
                if (!isFullyPaid) {
                    div.onmouseover = function() {
                        this.style.background = 'rgba(255,255,255,0.1)';
                    };
                    div.onmouseout = function() {
                        this.style.background = 'transparent';
                    };
                }
                dropdownList.appendChild(div);
            });
            updateSelectedMonths();
        } else {
            monthContainer.style.display = 'none';

            if (category === 'Quarterly') {
                const quarterIndex = Math.floor(monthIndex / 3);
                const quarters = ['Q1 (Jan-Mar)', 'Q2 (Apr-Jun)', 'Q3 (Jul-Sep)', 'Q4 (Oct-Dec)'];
                period = quarters[quarterIndex];
            } else if (category === 'Half-Yearly') {
                const halfIndex = monthIndex < 6 ? 0 : 1;
                const halfYears = ['H1 (Jan-Jun)', 'H2 (Jul-Dec)'];
                period = halfYears[halfIndex];
            } else if (category === 'Yearly') {
                period = year.toString();
            }
            hiddenMonth.value = period;
            calculateTotal();
        }
    }

    function updateSelectedMonths() {
        const checkboxes = document.querySelectorAll('.month-checkbox:checked');
        const selected = Array.from(checkboxes).map(cb => cb.getAttribute('data-display-text'));

        document.getElementById('hiddenMonthInput').value = selected.join(', ');
        const text = selected.length > 0 ? selected.join(', ') : 'Select Months';
        document.getElementById('selectedMonthsText').textContent = text;
        calculateTotal();
    }

    function updatePartialAmount(input) {
        const tr = input.closest('tr');
        tr.dataset.actual = input.value;
        calculateTotal();
    }

    function calculateTotal() {
        let subtotal = 0;
        const category = document.getElementById('feeCategorySelect').value;
        const isMonthly = category.toLowerCase() === 'monthly';

        if (isMonthly) {
            const selectedMonthTexts = Array.from(document.querySelectorAll('.month-checkbox:checked')).map(cb => cb
                .dataset.displayText);

            document.querySelectorAll('.main-fee-row').forEach(row => {
                const actual = parseFloat(row.dataset.actual) || 0;
                const permanentDiscount = parseFloat(row.dataset.discount) || 0;
                const discountedFee = Math.max(0, actual - permanentDiscount);
                const feeName = row.dataset.feeName;

                const feeType = (row.dataset.type || 'Monthly').toLowerCase();
                let totalForThisFee = 0;
                let validMonthCount = 0;

                if (feeType === 'monthly') {
                    const targetFeeName = feeName.toLowerCase();
                    selectedMonthTexts.forEach(monthText => {
                        const paidFees = currentPaidFeeTracker[monthText] || [];
                        const isPaid = paidFees.some(pf => pf.toLowerCase() === targetFeeName) ||
                            paidFees.includes('__ALL__');
                        if (!isPaid) validMonthCount++;
                    });
                    totalForThisFee = discountedFee * validMonthCount;
                } else {
                    totalForThisFee = discountedFee;
                    validMonthCount = 1;
                }

                subtotal += totalForThisFee;
                row.dataset.calculatedAmount = totalForThisFee;

                const actionCell = row.querySelector('td:nth-child(3)');
                if (actionCell) {
                    if (feeType !== 'monthly' || selectedMonthTexts.length > 0) {
                        if (feeType === 'monthly' && validMonthCount === 0) {
                            actionCell.innerHTML =
                                '<span style="color:#4caf50; font-weight:bold; background:rgba(76,175,80,0.1); padding:4px 8px; border-radius:4px; border:1px solid #4caf50;">Paid</span>';
                            row.style.opacity = '0.5';
                        } else {
                            row.style.opacity = '1';
                            const isPartial = feeType === 'monthly' && validMonthCount < selectedMonthTexts
                                .length;
                            let badgeHtml = '';
                            if (isPartial) badgeHtml +=
                                `<span style="font-size:10px; background:rgba(255,193,7,0.2); color:#ffc107; padding:1px 4px; border-radius:3px; margin-right:4px; border:1px solid rgba(255,193,7,0.3);">Partial</span>`;
                            if (feeType === 'monthly' && validMonthCount > 1) badgeHtml +=
                                `<span style="font-size:11px; color:var(--muted); margin-right:4px;">(x${validMonthCount})</span>`;

                            const removeBtnHtml = `
                            <button type="button" onclick="removeMainFee('${feeName}')"
                                    style="background:rgba(255,78,78,0.2); color:var(--danger); border:1px solid var(--danger); border-radius:4px; padding:4px 8px; cursor:pointer; font-size:11px; transition:all 0.2s;"
                                    onmouseover="this.style.background='rgba(255,78,78,0.3)'"
                                    onmouseout="this.style.background='rgba(255,78,78,0.2)'">
                              ✕ Remove
                            </button>`;
                            actionCell.innerHTML = `
                            <div style="display:flex; align-items:center; justify-content:flex-end; gap:8px;">
                                ${badgeHtml}
                                <span style="font-weight:bold; color:var(--text);">${totalForThisFee > 0 ? '৳'+totalForThisFee.toFixed(2) : ''}</span>
                                ${removeBtnHtml}
                            </div>`;
                        }
                    } else {
                        actionCell.innerHTML = '<span style="color:var(--muted)">Select Month</span>';
                        row.dataset.calculatedAmount = 0;
                        row.style.opacity = '1';
                    }
                }
            });
        } else {
            document.querySelectorAll('.main-fee-row').forEach(row => {
                const actual = parseFloat(row.dataset.actual) || 0;
                const permanentDiscount = parseFloat(row.dataset.discount) || 0;
                const discountedFee = Math.max(0, actual - permanentDiscount);
                subtotal += discountedFee;
                row.dataset.calculatedAmount = discountedFee;
                row.style.opacity = '1';
            });
        }

        document.querySelectorAll('.added-other-fee').forEach(row => {
            const feeName = row.getAttribute('data-fee-name');
            const feeItem = document.querySelector(`.other-fee-item[data-fee-name="${feeName}"]`);
            let amount = 0;
            if (row.dataset.actual) {
                const actual = parseFloat(row.dataset.actual) || 0;
                const discount = parseFloat(row.dataset.discount) || 0;
                amount = Math.max(0, actual - discount);
            } else if (feeItem) {
                amount = parseFloat(feeItem.getAttribute('data-discounted')) || 0;
            }
            subtotal += amount;
        });

        const manualDiscountInput = document.getElementById('manualDiscountInput');
        let manualDiscount = parseFloat(manualDiscountInput.value) || 0;

        currentNetPayable = Math.max(0, subtotal - manualDiscount);
        document.getElementById('summarySubtotal').textContent = '৳ ' + subtotal.toFixed(2);
        document.getElementById('payAmountInput').value = currentNetPayable;
    }

    function preparePaymentDetails() {
        const category = document.getElementById('feeCategorySelect').value;
        const paymentDetails = {
            category: category,
            fee_details: []
        };
        const isMonthly = category.toLowerCase() === 'monthly';

        if (isMonthly) {
            const selectedMonths = [];
            document.querySelectorAll('.month-checkbox:checked').forEach(cb => {
                selectedMonths.push({
                    name: cb.value,
                    year: cb.dataset.year
                });
            });
            document.getElementById('selectedMonthsInput').value = JSON.stringify(selectedMonths);
        }

        document.querySelectorAll('.main-fee-row').forEach(row => {
            let feeName = row.dataset.feeName || row.querySelector('td').textContent.trim();
            if (row.dataset.partName) feeName = feeName + ' - ' + row.dataset.partName;
            const actual = parseFloat(row.dataset.actual) || 0;
            const discount = parseFloat(row.dataset.discount) || 0;
            const discountedAmount = Math.max(0, actual - discount);
            const targetFeeName = feeName.toLowerCase();

            if (isMonthly) {
                const rowType = (row.dataset.type || 'Monthly').toLowerCase();
                if (rowType !== 'monthly') {
                    paymentDetails.fee_details.push({
                        name: feeName,
                        type: row.dataset.type || 'Other',
                        amount: discountedAmount,
                        original_amount: actual,
                        discount: discount
                    });
                } else {
                    document.querySelectorAll('.month-checkbox:checked').forEach(cb => {
                        const monthText = cb.dataset.displayText;
                        const paidFees = currentPaidFeeTracker[monthText] || [];
                        const isPaid = paidFees.some(pf => pf.toLowerCase() === targetFeeName) ||
                            paidFees.includes('__ALL__');
                        if (!isPaid) {
                            paymentDetails.fee_details.push({
                                name: feeName + ' - ' + monthText,
                                type: 'Monthly',
                                amount: discountedAmount,
                                original_amount: actual,
                                discount: discount,
                                month: cb.value,
                                year: cb.dataset.year
                            });
                        }
                    });
                }
            } else {
                paymentDetails.fee_details.push({
                    name: feeName,
                    type: category,
                    amount: discountedAmount,
                    original_amount: actual,
                    discount: discount
                });
            }
        });

        document.querySelectorAll('.added-other-fee').forEach(row => {
            const originalFeeName = row.getAttribute('data-fee-name');
            let feeName = originalFeeName;
            if (row.dataset.partName) feeName = originalFeeName + ' - ' + row.dataset.partName;
            const feeItem = document.querySelector(`.other-fee-item[data-fee-name="${originalFeeName}"]`);

            let actual = 0,
                discount = 0,
                valid = false;
            if (row.dataset.actual) {
                actual = parseFloat(row.dataset.actual) || 0;
                discount = parseFloat(row.dataset.discount) || 0;
                valid = true;
            } else if (feeItem) {
                actual = parseFloat(feeItem.getAttribute('data-actual')) || 0;
                discount = parseFloat(feeItem.getAttribute('data-discount')) || 0;
                valid = true;
            }

            if (valid) {
                const discountedAmount = Math.max(0, actual - discount);
                const type = (feeItem ? feeItem.getAttribute('data-type') : '') || row.dataset.type || 'Other';
                paymentDetails.fee_details.push({
                    name: feeName,
                    type: type,
                    amount: discountedAmount,
                    original_amount: actual,
                    discount: discount
                });
            }
        });

        const hiddenMonth = document.getElementById('hiddenMonthInput');
        if (hiddenMonth && !hiddenMonth.value && paymentDetails.fee_details.length > 0) {
            hiddenMonth.value = 'Other Fees';
        }

        document.getElementById('paymentDetailsInput').value = JSON.stringify(paymentDetails);

        setTimeout(() => {
            window.location.reload();
        }, 1500);
        return true;
    }
</script>
